// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCategoryRepository is an autogenerated mock type for the CategoryRepository type
type MockCategoryRepository struct {
	mock.Mock
}

type MockCategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryRepository) EXPECT() *MockCategoryRepository_Expecter {
	return &MockCategoryRepository_Expecter{mock: &_m.Mock}
}

// CheckCategoriesExist provides a mock function with given fields: ctx, categoryIDs
func (_m *MockCategoryRepository) CheckCategoriesExist(ctx context.Context, categoryIDs []int64) (bool, error) {
	ret := _m.Called(ctx, categoryIDs)

	if len(ret) == 0 {
		panic("no return value specified for CheckCategoriesExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) (bool, error)); ok {
		return rf(ctx, categoryIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) bool); ok {
		r0 = rf(ctx, categoryIDs)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, categoryIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryRepository_CheckCategoriesExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckCategoriesExist'
type MockCategoryRepository_CheckCategoriesExist_Call struct {
	*mock.Call
}

// CheckCategoriesExist is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryIDs []int64
func (_e *MockCategoryRepository_Expecter) CheckCategoriesExist(ctx interface{}, categoryIDs interface{}) *MockCategoryRepository_CheckCategoriesExist_Call {
	return &MockCategoryRepository_CheckCategoriesExist_Call{Call: _e.mock.On("CheckCategoriesExist", ctx, categoryIDs)}
}

func (_c *MockCategoryRepository_CheckCategoriesExist_Call) Run(run func(ctx context.Context, categoryIDs []int64)) *MockCategoryRepository_CheckCategoriesExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int64))
	})
	return _c
}

func (_c *MockCategoryRepository_CheckCategoriesExist_Call) Return(_a0 bool, _a1 error) *MockCategoryRepository_CheckCategoriesExist_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryRepository_CheckCategoriesExist_Call) RunAndReturn(run func(context.Context, []int64) (bool, error)) *MockCategoryRepository_CheckCategoriesExist_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryRepository creates a new instance of MockCategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryRepository {
	mock := &MockCategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
