// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "goshop/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"

	types "goshop/internal/domain/types"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// AddProductToCategories provides a mock function with given fields: ctx, productID, categoryIDs
func (_m *MockProductRepository) AddProductToCategories(ctx context.Context, productID int64, categoryIDs []int64) error {
	ret := _m.Called(ctx, productID, categoryIDs)

	if len(ret) == 0 {
		panic("no return value specified for AddProductToCategories")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []int64) error); ok {
		r0 = rf(ctx, productID, categoryIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_AddProductToCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProductToCategories'
type MockProductRepository_AddProductToCategories_Call struct {
	*mock.Call
}

// AddProductToCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int64
//   - categoryIDs []int64
func (_e *MockProductRepository_Expecter) AddProductToCategories(ctx interface{}, productID interface{}, categoryIDs interface{}) *MockProductRepository_AddProductToCategories_Call {
	return &MockProductRepository_AddProductToCategories_Call{Call: _e.mock.On("AddProductToCategories", ctx, productID, categoryIDs)}
}

func (_c *MockProductRepository_AddProductToCategories_Call) Run(run func(ctx context.Context, productID int64, categoryIDs []int64)) *MockProductRepository_AddProductToCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]int64))
	})
	return _c
}

func (_c *MockProductRepository_AddProductToCategories_Call) Return(_a0 error) *MockProductRepository_AddProductToCategories_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_AddProductToCategories_Call) RunAndReturn(run func(context.Context, int64, []int64) error) *MockProductRepository_AddProductToCategories_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function with given fields: ctx, _a1
func (_m *MockProductRepository) CreateProduct(ctx context.Context, _a1 *entities.Product) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Product) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockProductRepository_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entities.Product
func (_e *MockProductRepository_Expecter) CreateProduct(ctx interface{}, _a1 interface{}) *MockProductRepository_CreateProduct_Call {
	return &MockProductRepository_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, _a1)}
}

func (_c *MockProductRepository_CreateProduct_Call) Run(run func(ctx context.Context, _a1 *entities.Product)) *MockProductRepository_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Product))
	})
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) Return(_a0 error) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_CreateProduct_Call) RunAndReturn(run func(context.Context, *entities.Product) error) *MockProductRepository_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) DeleteProduct(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockProductRepository_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProductRepository_Expecter) DeleteProduct(ctx interface{}, id interface{}) *MockProductRepository_DeleteProduct_Call {
	return &MockProductRepository_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *MockProductRepository_DeleteProduct_Call) Run(run func(ctx context.Context, id int64)) *MockProductRepository_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductRepository_DeleteProduct_Call) Return(_a0 error) *MockProductRepository_DeleteProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_DeleteProduct_Call) RunAndReturn(run func(context.Context, int64) error) *MockProductRepository_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) GetProductByID(ctx context.Context, id int64) (*entities.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *entities.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockProductRepository_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockProductRepository_Expecter) GetProductByID(ctx interface{}, id interface{}) *MockProductRepository_GetProductByID_Call {
	return &MockProductRepository_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *MockProductRepository_GetProductByID_Call) Run(run func(ctx context.Context, id int64)) *MockProductRepository_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductRepository_GetProductByID_Call) Return(_a0 *entities.Product, _a1 error) *MockProductRepository_GetProductByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetProductByID_Call) RunAndReturn(run func(context.Context, int64) (*entities.Product, error)) *MockProductRepository_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductCategories provides a mock function with given fields: ctx, productID
func (_m *MockProductRepository) GetProductCategories(ctx context.Context, productID int64) ([]*entities.Category, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductCategories")
	}

	var r0 []*entities.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*entities.Category, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entities.Category); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_GetProductCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductCategories'
type MockProductRepository_GetProductCategories_Call struct {
	*mock.Call
}

// GetProductCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int64
func (_e *MockProductRepository_Expecter) GetProductCategories(ctx interface{}, productID interface{}) *MockProductRepository_GetProductCategories_Call {
	return &MockProductRepository_GetProductCategories_Call{Call: _e.mock.On("GetProductCategories", ctx, productID)}
}

func (_c *MockProductRepository_GetProductCategories_Call) Run(run func(ctx context.Context, productID int64)) *MockProductRepository_GetProductCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductRepository_GetProductCategories_Call) Return(_a0 []*entities.Category, _a1 error) *MockProductRepository_GetProductCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_GetProductCategories_Call) RunAndReturn(run func(context.Context, int64) ([]*entities.Category, error)) *MockProductRepository_GetProductCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetProducts provides a mock function with given fields: ctx, filters
func (_m *MockProductRepository) GetProducts(ctx context.Context, filters types.ProductFilters) ([]*entities.Product, int, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []*entities.Product
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ProductFilters) ([]*entities.Product, int, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ProductFilters) []*entities.Product); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ProductFilters) int); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, types.ProductFilters) error); ok {
		r2 = rf(ctx, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProductRepository_GetProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProducts'
type MockProductRepository_GetProducts_Call struct {
	*mock.Call
}

// GetProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - filters types.ProductFilters
func (_e *MockProductRepository_Expecter) GetProducts(ctx interface{}, filters interface{}) *MockProductRepository_GetProducts_Call {
	return &MockProductRepository_GetProducts_Call{Call: _e.mock.On("GetProducts", ctx, filters)}
}

func (_c *MockProductRepository_GetProducts_Call) Run(run func(ctx context.Context, filters types.ProductFilters)) *MockProductRepository_GetProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ProductFilters))
	})
	return _c
}

func (_c *MockProductRepository_GetProducts_Call) Return(_a0 []*entities.Product, _a1 int, _a2 error) *MockProductRepository_GetProducts_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProductRepository_GetProducts_Call) RunAndReturn(run func(context.Context, types.ProductFilters) ([]*entities.Product, int, error)) *MockProductRepository_GetProducts_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProductFromCategories provides a mock function with given fields: ctx, productID
func (_m *MockProductRepository) RemoveProductFromCategories(ctx context.Context, productID int64) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProductFromCategories")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_RemoveProductFromCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProductFromCategories'
type MockProductRepository_RemoveProductFromCategories_Call struct {
	*mock.Call
}

// RemoveProductFromCategories is a helper method to define mock.On call
//   - ctx context.Context
//   - productID int64
func (_e *MockProductRepository_Expecter) RemoveProductFromCategories(ctx interface{}, productID interface{}) *MockProductRepository_RemoveProductFromCategories_Call {
	return &MockProductRepository_RemoveProductFromCategories_Call{Call: _e.mock.On("RemoveProductFromCategories", ctx, productID)}
}

func (_c *MockProductRepository_RemoveProductFromCategories_Call) Run(run func(ctx context.Context, productID int64)) *MockProductRepository_RemoveProductFromCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockProductRepository_RemoveProductFromCategories_Call) Return(_a0 error) *MockProductRepository_RemoveProductFromCategories_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_RemoveProductFromCategories_Call) RunAndReturn(run func(context.Context, int64) error) *MockProductRepository_RemoveProductFromCategories_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function with given fields: ctx, _a1
func (_m *MockProductRepository) UpdateProduct(ctx context.Context, _a1 *entities.Product) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Product) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockProductRepository_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entities.Product
func (_e *MockProductRepository_Expecter) UpdateProduct(ctx interface{}, _a1 interface{}) *MockProductRepository_UpdateProduct_Call {
	return &MockProductRepository_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, _a1)}
}

func (_c *MockProductRepository_UpdateProduct_Call) Run(run func(ctx context.Context, _a1 *entities.Product)) *MockProductRepository_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Product))
	})
	return _c
}

func (_c *MockProductRepository_UpdateProduct_Call) Return(_a0 error) *MockProductRepository_UpdateProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_UpdateProduct_Call) RunAndReturn(run func(context.Context, *entities.Product) error) *MockProductRepository_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
