// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "goshop/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderItemRepository is an autogenerated mock type for the OrderItemRepository type
type MockOrderItemRepository struct {
	mock.Mock
}

type MockOrderItemRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderItemRepository) EXPECT() *MockOrderItemRepository_Expecter {
	return &MockOrderItemRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, items
func (_m *MockOrderItemRepository) Create(ctx context.Context, items []*entities.OrderItem) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*entities.OrderItem) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderItemRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderItemRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - items []*entities.OrderItem
func (_e *MockOrderItemRepository_Expecter) Create(ctx interface{}, items interface{}) *MockOrderItemRepository_Create_Call {
	return &MockOrderItemRepository_Create_Call{Call: _e.mock.On("Create", ctx, items)}
}

func (_c *MockOrderItemRepository_Create_Call) Run(run func(ctx context.Context, items []*entities.OrderItem)) *MockOrderItemRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*entities.OrderItem))
	})
	return _c
}

func (_c *MockOrderItemRepository_Create_Call) Return(_a0 error) *MockOrderItemRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderItemRepository_Create_Call) RunAndReturn(run func(context.Context, []*entities.OrderItem) error) *MockOrderItemRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderItemRepository creates a new instance of MockOrderItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderItemRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderItemRepository {
	mock := &MockOrderItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
