// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "goshop/internal/dto"

	entities "goshop/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// CreateCategory provides a mock function with given fields: ctx, req
func (_m *MockCategoryService) CreateCategory(ctx context.Context, req *dto.CreateCategoryRequest) (*entities.Category, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 *entities.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCategoryRequest) (*entities.Category, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.CreateCategoryRequest) *entities.Category); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.CreateCategoryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_CreateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCategory'
type MockCategoryService_CreateCategory_Call struct {
	*mock.Call
}

// CreateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - req *dto.CreateCategoryRequest
func (_e *MockCategoryService_Expecter) CreateCategory(ctx interface{}, req interface{}) *MockCategoryService_CreateCategory_Call {
	return &MockCategoryService_CreateCategory_Call{Call: _e.mock.On("CreateCategory", ctx, req)}
}

func (_c *MockCategoryService_CreateCategory_Call) Run(run func(ctx context.Context, req *dto.CreateCategoryRequest)) *MockCategoryService_CreateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dto.CreateCategoryRequest))
	})
	return _c
}

func (_c *MockCategoryService_CreateCategory_Call) Return(_a0 *entities.Category, _a1 error) *MockCategoryService_CreateCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_CreateCategory_Call) RunAndReturn(run func(context.Context, *dto.CreateCategoryRequest) (*entities.Category, error)) *MockCategoryService_CreateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCategory provides a mock function with given fields: ctx, id
func (_m *MockCategoryService) DeleteCategory(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_DeleteCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCategory'
type MockCategoryService_DeleteCategory_Call struct {
	*mock.Call
}

// DeleteCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCategoryService_Expecter) DeleteCategory(ctx interface{}, id interface{}) *MockCategoryService_DeleteCategory_Call {
	return &MockCategoryService_DeleteCategory_Call{Call: _e.mock.On("DeleteCategory", ctx, id)}
}

func (_c *MockCategoryService_DeleteCategory_Call) Run(run func(ctx context.Context, id int64)) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCategoryService_DeleteCategory_Call) Return(_a0 error) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_DeleteCategory_Call) RunAndReturn(run func(context.Context, int64) error) *MockCategoryService_DeleteCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCategories provides a mock function with given fields: ctx
func (_m *MockCategoryService) GetAllCategories(ctx context.Context) ([]*entities.CategoryWithCount, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []*entities.CategoryWithCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*entities.CategoryWithCount, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*entities.CategoryWithCount); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.CategoryWithCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_GetAllCategories_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCategories'
type MockCategoryService_GetAllCategories_Call struct {
	*mock.Call
}

// GetAllCategories is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCategoryService_Expecter) GetAllCategories(ctx interface{}) *MockCategoryService_GetAllCategories_Call {
	return &MockCategoryService_GetAllCategories_Call{Call: _e.mock.On("GetAllCategories", ctx)}
}

func (_c *MockCategoryService_GetAllCategories_Call) Run(run func(ctx context.Context)) *MockCategoryService_GetAllCategories_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockCategoryService_GetAllCategories_Call) Return(_a0 []*entities.CategoryWithCount, _a1 error) *MockCategoryService_GetAllCategories_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_GetAllCategories_Call) RunAndReturn(run func(context.Context) ([]*entities.CategoryWithCount, error)) *MockCategoryService_GetAllCategories_Call {
	_c.Call.Return(run)
	return _c
}

// GetCategoryByID provides a mock function with given fields: ctx, id
func (_m *MockCategoryService) GetCategoryByID(ctx context.Context, id int64) (*entities.CategoryWithCount, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *entities.CategoryWithCount
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.CategoryWithCount, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.CategoryWithCount); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CategoryWithCount)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCategoryService_GetCategoryByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCategoryByID'
type MockCategoryService_GetCategoryByID_Call struct {
	*mock.Call
}

// GetCategoryByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockCategoryService_Expecter) GetCategoryByID(ctx interface{}, id interface{}) *MockCategoryService_GetCategoryByID_Call {
	return &MockCategoryService_GetCategoryByID_Call{Call: _e.mock.On("GetCategoryByID", ctx, id)}
}

func (_c *MockCategoryService_GetCategoryByID_Call) Run(run func(ctx context.Context, id int64)) *MockCategoryService_GetCategoryByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockCategoryService_GetCategoryByID_Call) Return(_a0 *entities.CategoryWithCount, _a1 error) *MockCategoryService_GetCategoryByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCategoryService_GetCategoryByID_Call) RunAndReturn(run func(context.Context, int64) (*entities.CategoryWithCount, error)) *MockCategoryService_GetCategoryByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCategory provides a mock function with given fields: ctx, _a1
func (_m *MockCategoryService) UpdateCategory(ctx context.Context, _a1 *entities.Category) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entities.Category) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCategoryService_UpdateCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCategory'
type MockCategoryService_UpdateCategory_Call struct {
	*mock.Call
}

// UpdateCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *entities.Category
func (_e *MockCategoryService_Expecter) UpdateCategory(ctx interface{}, _a1 interface{}) *MockCategoryService_UpdateCategory_Call {
	return &MockCategoryService_UpdateCategory_Call{Call: _e.mock.On("UpdateCategory", ctx, _a1)}
}

func (_c *MockCategoryService_UpdateCategory_Call) Run(run func(ctx context.Context, _a1 *entities.Category)) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.Category))
	})
	return _c
}

func (_c *MockCategoryService_UpdateCategory_Call) Return(_a0 error) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCategoryService_UpdateCategory_Call) RunAndReturn(run func(context.Context, *entities.Category) error) *MockCategoryService_UpdateCategory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
