// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "goshop/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockRoleRepositoryInterface is an autogenerated mock type for the RoleRepositoryInterface type
type MockRoleRepositoryInterface struct {
	mock.Mock
}

type MockRoleRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoleRepositoryInterface) EXPECT() *MockRoleRepositoryInterface_Expecter {
	return &MockRoleRepositoryInterface_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockRoleRepositoryInterface) GetByID(ctx context.Context, id int64) (*entities.Role, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entities.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.Role, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.Role); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRoleRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockRoleRepositoryInterface_Expecter) GetByID(ctx interface{}, id interface{}) *MockRoleRepositoryInterface_GetByID_Call {
	return &MockRoleRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockRoleRepositoryInterface_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockRoleRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_GetByID_Call) Return(_a0 *entities.Role, _a1 error) *MockRoleRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryInterface_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*entities.Role, error)) *MockRoleRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *MockRoleRepositoryInterface) GetByName(ctx context.Context, name string) (*entities.Role, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *entities.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entities.Role, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entities.Role); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Role)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRoleRepositoryInterface_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockRoleRepositoryInterface_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRoleRepositoryInterface_Expecter) GetByName(ctx interface{}, name interface{}) *MockRoleRepositoryInterface_GetByName_Call {
	return &MockRoleRepositoryInterface_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *MockRoleRepositoryInterface_GetByName_Call) Run(run func(ctx context.Context, name string)) *MockRoleRepositoryInterface_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRoleRepositoryInterface_GetByName_Call) Return(_a0 *entities.Role, _a1 error) *MockRoleRepositoryInterface_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRoleRepositoryInterface_GetByName_Call) RunAndReturn(run func(context.Context, string) (*entities.Role, error)) *MockRoleRepositoryInterface_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRoleRepositoryInterface creates a new instance of MockRoleRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoleRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoleRepositoryInterface {
	mock := &MockRoleRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
