// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "goshop/internal/dto"

	entities "goshop/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// MockAddressServiceInterface is an autogenerated mock type for the AddressServiceInterface type
type MockAddressServiceInterface struct {
	mock.Mock
}

type MockAddressServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddressServiceInterface) EXPECT() *MockAddressServiceInterface_Expecter {
	return &MockAddressServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateAddress provides a mock function with given fields: ctx, userID, req
func (_m *MockAddressServiceInterface) CreateAddress(ctx context.Context, userID int64, req *dto.CreateAddressRequest) (*entities.UserAddress, error) {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateAddress")
	}

	var r0 *entities.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.CreateAddressRequest) (*entities.UserAddress, error)); ok {
		return rf(ctx, userID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, *dto.CreateAddressRequest) *entities.UserAddress); ok {
		r0 = rf(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, *dto.CreateAddressRequest) error); ok {
		r1 = rf(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddressServiceInterface_CreateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAddress'
type MockAddressServiceInterface_CreateAddress_Call struct {
	*mock.Call
}

// CreateAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - req *dto.CreateAddressRequest
func (_e *MockAddressServiceInterface_Expecter) CreateAddress(ctx interface{}, userID interface{}, req interface{}) *MockAddressServiceInterface_CreateAddress_Call {
	return &MockAddressServiceInterface_CreateAddress_Call{Call: _e.mock.On("CreateAddress", ctx, userID, req)}
}

func (_c *MockAddressServiceInterface_CreateAddress_Call) Run(run func(ctx context.Context, userID int64, req *dto.CreateAddressRequest)) *MockAddressServiceInterface_CreateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*dto.CreateAddressRequest))
	})
	return _c
}

func (_c *MockAddressServiceInterface_CreateAddress_Call) Return(_a0 *entities.UserAddress, _a1 error) *MockAddressServiceInterface_CreateAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddressServiceInterface_CreateAddress_Call) RunAndReturn(run func(context.Context, int64, *dto.CreateAddressRequest) (*entities.UserAddress, error)) *MockAddressServiceInterface_CreateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAddress provides a mock function with given fields: ctx, userID, addressID
func (_m *MockAddressServiceInterface) DeleteAddress(ctx context.Context, userID int64, addressID int64) error {
	ret := _m.Called(ctx, userID, addressID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAddress")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, addressID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAddressServiceInterface_DeleteAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAddress'
type MockAddressServiceInterface_DeleteAddress_Call struct {
	*mock.Call
}

// DeleteAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - addressID int64
func (_e *MockAddressServiceInterface_Expecter) DeleteAddress(ctx interface{}, userID interface{}, addressID interface{}) *MockAddressServiceInterface_DeleteAddress_Call {
	return &MockAddressServiceInterface_DeleteAddress_Call{Call: _e.mock.On("DeleteAddress", ctx, userID, addressID)}
}

func (_c *MockAddressServiceInterface_DeleteAddress_Call) Run(run func(ctx context.Context, userID int64, addressID int64)) *MockAddressServiceInterface_DeleteAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockAddressServiceInterface_DeleteAddress_Call) Return(_a0 error) *MockAddressServiceInterface_DeleteAddress_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAddressServiceInterface_DeleteAddress_Call) RunAndReturn(run func(context.Context, int64, int64) error) *MockAddressServiceInterface_DeleteAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddressByID provides a mock function with given fields: ctx, addressID
func (_m *MockAddressServiceInterface) GetAddressByID(ctx context.Context, addressID int64) (*entities.UserAddress, error) {
	ret := _m.Called(ctx, addressID)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressByID")
	}

	var r0 *entities.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entities.UserAddress, error)); ok {
		return rf(ctx, addressID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entities.UserAddress); ok {
		r0 = rf(ctx, addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddressServiceInterface_GetAddressByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressByID'
type MockAddressServiceInterface_GetAddressByID_Call struct {
	*mock.Call
}

// GetAddressByID is a helper method to define mock.On call
//   - ctx context.Context
//   - addressID int64
func (_e *MockAddressServiceInterface_Expecter) GetAddressByID(ctx interface{}, addressID interface{}) *MockAddressServiceInterface_GetAddressByID_Call {
	return &MockAddressServiceInterface_GetAddressByID_Call{Call: _e.mock.On("GetAddressByID", ctx, addressID)}
}

func (_c *MockAddressServiceInterface_GetAddressByID_Call) Run(run func(ctx context.Context, addressID int64)) *MockAddressServiceInterface_GetAddressByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAddressServiceInterface_GetAddressByID_Call) Return(_a0 *entities.UserAddress, _a1 error) *MockAddressServiceInterface_GetAddressByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddressServiceInterface_GetAddressByID_Call) RunAndReturn(run func(context.Context, int64) (*entities.UserAddress, error)) *MockAddressServiceInterface_GetAddressByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAddressByIDForUser provides a mock function with given fields: ctx, userID, addressID
func (_m *MockAddressServiceInterface) GetAddressByIDForUser(ctx context.Context, userID int64, addressID int64) (*entities.UserAddress, error) {
	ret := _m.Called(ctx, userID, addressID)

	if len(ret) == 0 {
		panic("no return value specified for GetAddressByIDForUser")
	}

	var r0 *entities.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entities.UserAddress, error)); ok {
		return rf(ctx, userID, addressID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entities.UserAddress); ok {
		r0 = rf(ctx, userID, addressID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userID, addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddressServiceInterface_GetAddressByIDForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAddressByIDForUser'
type MockAddressServiceInterface_GetAddressByIDForUser_Call struct {
	*mock.Call
}

// GetAddressByIDForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - addressID int64
func (_e *MockAddressServiceInterface_Expecter) GetAddressByIDForUser(ctx interface{}, userID interface{}, addressID interface{}) *MockAddressServiceInterface_GetAddressByIDForUser_Call {
	return &MockAddressServiceInterface_GetAddressByIDForUser_Call{Call: _e.mock.On("GetAddressByIDForUser", ctx, userID, addressID)}
}

func (_c *MockAddressServiceInterface_GetAddressByIDForUser_Call) Run(run func(ctx context.Context, userID int64, addressID int64)) *MockAddressServiceInterface_GetAddressByIDForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockAddressServiceInterface_GetAddressByIDForUser_Call) Return(_a0 *entities.UserAddress, _a1 error) *MockAddressServiceInterface_GetAddressByIDForUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddressServiceInterface_GetAddressByIDForUser_Call) RunAndReturn(run func(context.Context, int64, int64) (*entities.UserAddress, error)) *MockAddressServiceInterface_GetAddressByIDForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserAddresses provides a mock function with given fields: ctx, userID
func (_m *MockAddressServiceInterface) GetUserAddresses(ctx context.Context, userID int64) ([]*entities.UserAddress, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserAddresses")
	}

	var r0 []*entities.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*entities.UserAddress, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*entities.UserAddress); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddressServiceInterface_GetUserAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserAddresses'
type MockAddressServiceInterface_GetUserAddresses_Call struct {
	*mock.Call
}

// GetUserAddresses is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *MockAddressServiceInterface_Expecter) GetUserAddresses(ctx interface{}, userID interface{}) *MockAddressServiceInterface_GetUserAddresses_Call {
	return &MockAddressServiceInterface_GetUserAddresses_Call{Call: _e.mock.On("GetUserAddresses", ctx, userID)}
}

func (_c *MockAddressServiceInterface_GetUserAddresses_Call) Run(run func(ctx context.Context, userID int64)) *MockAddressServiceInterface_GetUserAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *MockAddressServiceInterface_GetUserAddresses_Call) Return(_a0 []*entities.UserAddress, _a1 error) *MockAddressServiceInterface_GetUserAddresses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddressServiceInterface_GetUserAddresses_Call) RunAndReturn(run func(context.Context, int64) ([]*entities.UserAddress, error)) *MockAddressServiceInterface_GetUserAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAddress provides a mock function with given fields: ctx, userID, addressID, req
func (_m *MockAddressServiceInterface) UpdateAddress(ctx context.Context, userID int64, addressID int64, req *dto.UpdateAddressRequest) (*entities.UserAddress, error) {
	ret := _m.Called(ctx, userID, addressID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAddress")
	}

	var r0 *entities.UserAddress
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *dto.UpdateAddressRequest) (*entities.UserAddress, error)); ok {
		return rf(ctx, userID, addressID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, *dto.UpdateAddressRequest) *entities.UserAddress); ok {
		r0 = rf(ctx, userID, addressID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.UserAddress)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, *dto.UpdateAddressRequest) error); ok {
		r1 = rf(ctx, userID, addressID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddressServiceInterface_UpdateAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAddress'
type MockAddressServiceInterface_UpdateAddress_Call struct {
	*mock.Call
}

// UpdateAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - addressID int64
//   - req *dto.UpdateAddressRequest
func (_e *MockAddressServiceInterface_Expecter) UpdateAddress(ctx interface{}, userID interface{}, addressID interface{}, req interface{}) *MockAddressServiceInterface_UpdateAddress_Call {
	return &MockAddressServiceInterface_UpdateAddress_Call{Call: _e.mock.On("UpdateAddress", ctx, userID, addressID, req)}
}

func (_c *MockAddressServiceInterface_UpdateAddress_Call) Run(run func(ctx context.Context, userID int64, addressID int64, req *dto.UpdateAddressRequest)) *MockAddressServiceInterface_UpdateAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64), args[3].(*dto.UpdateAddressRequest))
	})
	return _c
}

func (_c *MockAddressServiceInterface_UpdateAddress_Call) Return(_a0 *entities.UserAddress, _a1 error) *MockAddressServiceInterface_UpdateAddress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddressServiceInterface_UpdateAddress_Call) RunAndReturn(run func(context.Context, int64, int64, *dto.UpdateAddressRequest) (*entities.UserAddress, error)) *MockAddressServiceInterface_UpdateAddress_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAddressServiceInterface creates a new instance of MockAddressServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddressServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddressServiceInterface {
	mock := &MockAddressServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
